@startuml prenoting-use-cases
  left to right direction
  skinparam packageStyle rectangle
  skinparam shadowing false
  skinparam usecase {
    BackgroundColor #FDFEFE
    BorderColor #1F4E79
  }
  actor "Paziente" as P
  actor "Medico" as D

  rectangle "app gestione appuntamenti" {
    package "Autenticazione & Account" {
      usecase "UC01 Registrazione" as UC01
      usecase "UC02 Effettuare login" as UC02
      usecase "UC03 Effettuare logout" as UC03
      usecase "UC04 Modifica password" as UC04
    }
    package "Area Paziente" {
      usecase "UC05 Visualizzare dashboard paziente" as UC05
      usecase "UC06 Aggiornare info paziente" as UC06
      usecase "UC07 Avviare prenotazione guidata" as UC07
      usecase "UC08 Modificare appuntamento" as UC08
      usecase "UC09 Annullare appuntamento" as UC09
    }
    package "Area Medico" {
      usecase "UC10 Visualizzare calendario" as UC10
      usecase "UC11 Visualizzare dettaglio appuntamento\ne dati paziente" as UC11
      usecase "UC12 Gestione disponibilità" as UC12
      usecase "UC13 Gestione tipi di visita" as UC13
    }
  }
  ' Paziente
  P --> UC01
  P --> UC02
  P --> UC03
  P --> UC04
  P --> UC05
  P --> UC06
  P --> UC07
  P --> UC08
  P --> UC09
  ' Medico
  D --> UC02
  D --> UC03
  D --> UC04
  D --> UC10
  D --> UC11
  D --> UC12
  D --> UC13
@enduml
